<?php

require_once dirname(__FILE__) . '/../../../Class/Doku/Php.php';

/**
 * Test class for Class_Doku_Php.
 * Generated by PHPUnit on 2011-01-23 at 23:39:53.
 */
class Class_Doku_PhpTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Class_Doku_Php
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Class_Doku_Php;
    }

    protected function getMockedSource()
    {
        return $source = $this->getMock('Class_Doku_Php_Source_Reflection');
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * test getFunctionDocumentation
     */
    public function testGetFunctionDocumentation() {
        $src = $this->getMockedSource();
        $description = new Class_Doku_Php_Description_ReflectionFunction();
        $src->expects($this->any())
            ->method('getFunctionDescription')
            ->with('substr')
            ->will($this->returnValue($description));
        $this->object->setSource($src);
        $this->assertSame($description, $this->object->getFunctionDocumentation('substr'));
    }

    /**
     * test getFunctionDocumentation without source adapter throws exception
     * @expectedException Class_Doku_Exception
     */
    public function testGetFunctionDocumentationWithoutSource()
    {
        $this->object->getFunctionDocumentation('is_array');
    }
    
    /**
     * test setSource
     */
    public function testSetSource() {
        $this->object->setSource($this->getMockedSource());
    }

    /**
     * test getSource
     */
    public function testGetSource() {
        $src = $this->getMockedSource();
        $this->object->setSource($src);
        $this->assertSame($src, $this->object->getSource());
    }

}

?>
