<?php


require_once dirname(__FILE__) . '/../../../../../Class/Doku/Php/Description/ReflectionFunction.php';

/**
 * Test class for Class_Doku_Php_Description_ReflectionFunction.
 * Generated by PHPUnit on 2011-01-24 at 00:55:21.
 */
class Class_Doku_Php_Description_ReflectionFunctionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Class_Doku_Php_Description_ReflectionFunction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Class_Doku_Php_Description_ReflectionFunction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * test setFunction
     * @covers Class_Doku_Php_Description_ReflectionFunction::getFunction
     */
    public function testSetFunction() 
    {
        $function = new ReflectionFunction('substr');
        $this->object->setFunction($function);
        $this->assertSame($function, $this->object->getFunction());
    }

    /**
     * test magical to string
     */
    public function test__toString() {
        $function = new ReflectionFunction('substr');
        $this->object->setFunction($function);
        
        $this->assertGreaterThan(0, strlen($this->object->__toString()));
    }
    
    public function testToStringEmptyWithoutFunction()
    {
        $this->assertEquals('', $this->object->__toString());
    }

}

?>
