<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-30 at 11:47:04.
 */
class Class_Doku_Php_Source_PHPDotNetTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Class_Doku_Php_Source_PHPDotNet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Class_Doku_Php_Source_PHPDotNet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * if no referencefile was set the default one is to be returned
     */
    public function testGetReferenceFile()
    {
        $this->assertEquals(
            Class_Doku_Php_Source_PHPDotNet::DEFAULT_REFERENCE_PATH,
            $this->object->getReferenceFile()
        );
    }

    /**
     *
     */
    public function testGetFunctionDescription()
    {
        $this->object->setReferenceFile('tests/fixtures/php-ref.json');
        $functionName = 'socket_getpeername';
        $function = $this->object->getFunctionDescription($functionName);
        $this->assertInstanceOf(
            'Class_Doku_Php_Description_JsonFunction',
            $function
        );
        $this->assertContains($functionName, (string)$function);
    }

    /**
     * if function was not found, link to php.net should be rendered.
     */
    public function testGetFunctionDescriptionFunctionNotFound()
    {
        $this->object->setReferenceFile('tests/fixtures/php-ref.json');
        $functionName = 'file_exists';
        $function = $this->object->getFunctionDescription($functionName);
        $this->assertInstanceOf(
            'Class_Doku_Php_Description_PHPDotNetLink',
            $function
        );
    }
}
